source "https://rubygems.org"
source "http://gems.github.com"

gem "thin"
gem "sinatra"
gem "haml"
gem "log4r"
gem "sbfaulkner-sinatra-prawn", require: "sinatra/prawn"
gem "data_mapper"
gem "sinatra-contrib", github: "sinatra/sinatra-contrib"
gem "dm-sqlite-adapter"
